version: '2.1'

services:
  mqserver:
    image: rma/mq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    ports:
      - "1414:1414"
      - "9443:9443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/ibmmq/console"]
      interval: 10s
      timeout: 5s
      retries: 6

  application:
    image: rma/micronaut-jms-mq
    environment:
      - MQ_SERVER=mqserver
    restart: always
    ports:
      - "9191:8181"
    depends_on:
      mqserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8181/health"]
      interval: 10s
      timeout: 10s
      retries: 5